apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-task
spec:
  replicas: 2
  selector:
    matchLabels:
      app: get-task
  template:
    metadata:
      labels:
        app: get-task
    spec:
      containers:
      - name: get-task
        image: todoappacr777.azurecr.io/get-task:v1
        ports:
        - containerPort: 8000
        env:
        - name: CONNECTION_STRING
          value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:todoapp-sql-server777.database.windows.net,1433;Database=todoapp_db1322;Uid=devopsadmin;Pwd={your_password_here};Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
