apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gettask-ingress
  labels:
    app.kubernetes.io/name: gettask-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: gettask.devopsai.online
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: get-task-svc
            port: 
              number: 80
